[[pages]]
path = "about.py"
name = "Home"
icon = "ğŸ¾"

[[pages]]
path = "ingest_ui.py"
name = "Ingestion Pipeline"
icon = "ğŸš€"

[[pages]]
path = "core/validate.py"
name = "Validation"
icon = "âœï¸"

[[pages]]
path = "app/species_detection_ui.py"
name = "Species Detection"
icon = "ğŸ§¬"

[[pages]]
path = "search_ui.py"
name = "Exploration / Search"
icon = "ğŸ”"
